country_names:
  - Egypt
  - مصر
  - egypt
cities:
  - Cairo
  - Giza
  - Alexandria
  - القاهرة
  - الجيزة
  - الإسكندرية
accessible_keywords:
  - disability
  - disabilities
  - pwd
  - inclusive
  - accessibility
  - ذوي الهمم
  - إعاقة
  - معاق
